### PR TITLE
Editing and creating users.

### PR DESCRIPTION
**Pull request by itsbriany**
Motivation described by @urdaalex below :)

### CODE REVIEW

**Comment by Hexcles** [comment]
Hi Brian! Would you mind me asking what's the motivation of this change?

Use a single `createUser` method to create or edit users is indeed confusing, I agree. One way to improve is to change the name to something like `createOrUpdateUser`. Another way, the one you proposed, does come with some extra cost - we'll be issuing two HTTP requests instead of one every time we create/update users. And it is in fact almost impossible to guarantee the semantics, for example: a user could be created after `this.user` is called but before sending the creation request, in which case `createUser` becomes `editUser` again, and I don't think there's any way to prevent this.

**Comment by urdaalex** [comment]
@Hexcles Motivation of the change is to ultimately provide a (more intuitive) way to change the passwords of a user in rabbit ([example](https://github.com/taskcluster/taskcluster-pulse/blob/username-rotations/src/data.js#L69-L71)). As you can see, some of the understanding is lost when a user is updated with a method called createUser. The createOrUpdateUser would be the ideal solution i think.

**Comment by itsbriany** [comment]
I thought it would be more clear to have them as independent operations. However, as @Hexcles mentioned, there is consequentially an additional HTTP request performed. I'll see how I can change it to `createOrUpdateUser` instead to reduce overhead.

**Comment by Hexcles** [comment]
Thanks @itsbriany @urdaalex . Even I myself was confused for a sec when I saw some code in `api.js` (like "does it create a duplicate user?", "does it throw if the user already exist?".) Some clarification on this method can definitely help.

I think separating the create and edit semantics is generally a good idea provided that we could do it reliably. The one extra HTTP request is not the first concern IMHO. The real problem is, paying the cost for the extra HTTP request does not actually provide any guarantee.

I'll also try to find if the management API has anything helpful.

**Comment by imbstack** [comment]
This just needs updated to merge with master and we're good to go!

**Pull request closed without merging**
